[[redirects]]
from = "/admin"
to = "/admin/"
status = 301
force = true

[[redirects]]
from = "/"
to = "/blog"
status = 301
force = true

[[redirects]]
from = "https://blog.cupofdata.com"
to = "https://blog.cupofdata.com/blog/"
status = 301
force = true

[[redirects]]
from = "https://blog.cupofdata.com/"
to = "https://blog.cupofdata.com/blog/"
status = 301
force = true
